name: Helm Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check source code
        uses: actions/checkout@v3
        
      - name: Check Changes
        id: check
        run: |
          if [[ `git status --porcelain | grep charts/tekton-pipeline/Chart.yaml` ]]; then
            echo "OK: Changes detected."
          else
          echo "WARNING: No changes were detected."
          fi
        shell: bash
      
      - uses: J12934/helm-gh-pages-action@master
        with:
          charts-folder: "charts"
          deploy-branch: "gh-pages"
