name: Helm Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check source code
        uses: actions/checkout@v3
        
      - name: Read Helm Chart
        id: chart
        uses: jacobtomlinson/gha-read-helm-chart@master
        with:
          path: charts/tekton-pipeline
      - name: Print Out Chart Version
        run: echo "chart_version= ${{ steps.chart.outputs.version }}" >> "GITHUB_ENV"
      - name: use env
        run: |
            echo "${{ env.chart_version }}"
      
      - uses: J12934/helm-gh-pages-action@master
        with:
          charts-folder: "charts"
          deploy-branch: "gh-pages"
